export const PRODUCT_UPDATE_REQUEST ='PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS ='PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL ='PRODUCT_UPDATE_FAIL'
export const PRODUCT_CLEAR_UPDATE_STATE ='PRODUCT_CLEAR_UPDATE_STATE'

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_FORM_SUBMIT_REQUEST ='PRODUCT_FORM_SUBMIT_REQUEST'
export const PRODUCT_FORM_SUBMIT_SUCCESS ='PRODUCT_FORM_SUBMIT_SUCCESS'
export const PRODUCT_FORM_SUBMIT_FAIL ='PRODUCT_FORM_SUBMIT_FAIL'
export const PRODUCT_CLEAR_FORM_SUBMIT_STATE ='PRODUCT_CLEAR_FORM_SUBMIT_STATE'